# Generated by Django 3.1.2 on 2020-11-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marks',
            new_name='mark',
        ),
    ]
