# Generated by Django 3.1.2 on 2020-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20201126_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='biology',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='english',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='physics',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='social',
        ),
    ]
