# Generated by Django 3.1.2 on 2020-11-26 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0004_auto_20201126_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marks',
            new_name='Mark',
        ),
    ]
