# Generated by Django 3.1.2 on 2020-11-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201126_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='user',
        ),
    ]
