# Generated by Django 3.1.2 on 2020-11-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_mark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='biology',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='social',
            field=models.IntegerField(default=0),
        ),
    ]
