# Generated by Django 3.1.2 on 2020-12-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20201128_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
