# Generated by Django 3.1.2 on 2020-12-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0008_delete_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('math', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('english', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('social', models.IntegerField()),
            ],
        ),
    ]
