# Generated by Django 3.1.2 on 2020-12-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='id',
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
