# Generated by Django 3.1.2 on 2020-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20201206_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
